controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 50

    ridgeback_joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      # publish_rate: 50

    ridgeback_temp_controller:
      type: diff_drive_controller/DiffDriveController

    ridgeback_velocity_controller:
      type: mecanum_drive_controller/MecanumDriveController

ridgeback_velocity_controller:
  ros__parameters:
    # left_wheel_names: ["left_wheel"]
    # right_wheel_names: ["right_wheel"]
    wheel_names: ["front_left_wheel","rear_left_wheel","front_right_wheel","rear_right_wheel"]
    # front_left_wheel_joint: "front_left_wheel"
    # back_left_wheel_joint: "rear_left_wheel"
    # front_right_wheel_joint: "front_right_wheel"
    # back_right_wheel_joint: "rear_right_wheel"
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    cmd_vel_timeout: 0.25

    # Override URDF look-up for wheel separation since the parent link is not the base_link.
    wheel_separation_x: 0.638
    wheel_separation_y: 0.551

    # Odometry fused with IMU is published by robot_localization, so
    # no need to publish a TF based on encoders alone.
    enable_odom_tf: false

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits     : true
    linear.x.max_velocity            : 1.1   # m/s
    linear.x.has_acceleration_limits : true
    linear.x.max_acceleration        : 2.5   # m/s^2

    linear.y.has_velocity_limits     : true
    linear.y.max_velocity            : 1.1   # m/s
    linear.y.has_acceleration_limits : true
    linear.y.max_acceleration        : 2.5   # m/s^2

    angular.z.has_velocity_limits     : true
    angular.z.max_velocity            : 2.0   # rad/s
    angular.z.has_acceleration_limits : true
    angular.z.max_acceleration        : 1.0   # rad/s^2


ridgeback_temp_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel","rear_left_wheel"]
    right_wheel_names: ["front_right_wheel","rear_right_wheel"]
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    cmd_vel_timeout: 0.25
    use_stamped_vel: false

    enable_odom_tf: true

    wheel_separation: 0.638
    wheel_radius: 0.0759

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # TODO: measure on actual vehicle: how?
    linear.x.has_velocity_limits      : true
    linear.x.max_velocity             : 1.3   # m/s
    linear.x.has_acceleration_limits  : true
    linear.x.max_acceleration         : 1.0   # m/s^2
    linear.x.has_jerk_limits          : false
    # TODO: measure on actual vehicle: how?
    angular.z.has_velocity_limits     : true
    angular.z.max_velocity            : 4.0   # rad/s
    angular.z.has_acceleration_limits : true
    angular.z.max_acceleration        : 2.0   # rad/s^2
    angular.z.has_jerk_limits         : false

