# /teleop_twist_joy_node:
#ros__parameters:
 # axis_linear.x: 1
 # axis_angular.yaw: 0
 # scale_linear.x: 2.1
 # scale_angular.yaw: 2.0
 # enable_button: 0
 # require_enable_button: False
twist_mux:
  ros__parameters:
    topics:
      joy:
        topic   : joy_teleop/cmd_vel
        timeout : 0.5
        priority: 10
      bt_joy:
        topic   : bluetooth_teleop/cmd_vel
        timeout : 0.5
        priority: 9
      interactive_marker:
        topic   : twist_marker_server/cmd_vel
        timeout : 0.5
        priority: 8
      external:
        topic   : cmd_vel
        timeout : 0.5
        priority: 1
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255
